version: "3.8"

services:
  db:
    image: postgres:17-alpine
    container_name: wedding_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: wedding_user
      POSTGRES_PASSWORD: wedding_pass
      POSTGRES_DB: wedding_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: wedding_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

volumes:
  db_data:
